server:
  port: 8081
  servlet:
    context-path: /profile

spring:
  application:
    name: profile-service
  neo4j:
    uri: ${DBMS_CONNECTION_PROFILE:bolt://localhost:7687}
    authentication:
      username: ${DBMS_USERNAME_PROFILE:neo4j}
      password: ${DBMS_PASSWORD_PROFILE:12345678}

app:
  service:
    identity: ${CLIENT_URL_IDENTITY:http://localhost:8080/identity}

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"