server:
  port: 8888

app:
  api-prefix: /api/v1
  identity:
    base-url: ${IDENTITY_BASE_URL:http://localhost:8080/identity}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - name: CustomRateLimiterFilter
          args:
            redis-rate-limiter.replenishRate: 5
            redis-rate-limiter.burstCapacity: 10
            key-resolver: "#{@userKeyResolver}"

      routes:
        - id : identity_service
          uri : ${ROUTE_URI_IDENTITY:http://localhost:8080}
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id : profile_service
          uri : ${ROUTE_URI_PROFILE:http://localhost:8081}
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2
        - id: notification_service
          uri: ${ROUTE_URI_NOTIFICATION:http://localhost:8082}
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: post_service
          uri: ${ROUTE_URI_POST:http://localhost:8083}
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=2
        - id: wallet_service
          uri: ${ROUTE_URI_WALLET:http://localhost:8084}
          predicates:
            - Path=${app.api-prefix}/wallet/**
          filters:
            - StripPrefix=2
        - id: paypal_service
          uri: ${ROUTE_URI_PAYPAL:http://localhost:8085}
          predicates:
            - Path=${app.api-prefix}/payment-paypal/**
          filters:
            - StripPrefix=2
        - id: payment_service
          uri: ${ROUTE_URI_PAYMENT:http://localhost:8086}
          predicates:
            - Path=${app.api-prefix}/payment/**
          filters:
            - StripPrefix=2
  data:
    redis:
      host: ${HOST_REDIS:localhost}
      port: 6379
logging:
  level:
    com.microservice.gateway: DEBUG
