server:
  port: 8087
  servlet:
    context-path: /file
spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: ${DBMS_CONNECTION_FILE:mongodb://root:root@localhost:27017/file-service?authSource=admin}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"