server:
  port: 8084
  servlet:
    context-path: /wallet
spring:
  application:
    name: wallet-service
  datasource:
    url: ${DBMS_CONNECTION_WALLET:jdbc:mysql://localhost:3306/wallet_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD_WALLET:root}
    username: ${DBMS_USERNAME_WALLET:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${SERVER_PORT_KAFKA:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    redis:
      host: ${HOST_REDIS:localhost}
      port: 6379

app:
  service:
    identity: ${CLIENT_URL_IDENTITY:http://localhost:8080/identity}
    post: ${CLIENT_URL_POST:http://localhost:8083/post}
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

#resilience4j

resilience4j.retry:
  instances:
    restApi:
      max-attempts: 3
      wait-duration:
        seconds: 1
      retry-exceptions:
        - java.io.IOException
        - feign.FeignException
        - feign.RetryableException

resilience4j.circuitbreaker:
  instances:
    restCircuitBreaker:
      register-health-indicator: true
      sliding-window-size: 5
      permitted-number-of-calls-in-half-open-state: 3
      failure-rate-threshold: 50
      wait-duration-in-open-state:
        seconds: 10

