server:
  port: 8085
  servlet:
    context-path: /payment-paypal
spring:
  application:
    name: paypal-service
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/wallet_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:root}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
app:
  service:
    wallet: http://localhost:8084/wallet
    payment: http://localhost:8086/payment



jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

paypal:
  clientId: <client-id-sandbox>
  clientSecret: <client-secret-sandbox>
  redirectUrl: "http://localhost:3000/payment-complete"